

--- Cardinalidad UNO A MUCHOS
--- apiAgenciaAutos
--- 1 Marcas y * Modelos

CREATE TABLE MARCAS_AGEN(
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL,
ORIGEN VARCHAR2(90) NOT NULL,
FECHA_LANZ DATE
); 

---DROP TABLE MARCAS_AGEN;
---DROP TABLE MODELOS_AGEN;

INSERT INTO MARCAS_AGEN VALUES(1, 'TOYOTA', 'JAPON', '1993-02-02');
COMMIT;

SELECT * FROM MARCAS_AGEN;

CREATE TABLE MODELOS_AGEN(
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100) NOT NULL,
TRANSMISSION NVARCHAR2(90) NOT NULL,    
PRECIO NUMBER,
EXISTENCIA NUMBER NOT NULL,
ID_MARCA NUMBER NOT NULL,
FOREIGN KEY(ID_MARCA) REFERENCES MARCAS_AGEN(ID)
);

INSERT INTO MODELOS_AGEN VALUES(1,'TACOMA','AUTOMATICO',23000,100,1);
COMMIT;

SELECT * FROM MODELOS_AGEN;

